[package]
name = "get_accounts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "1.0.2"
ethers-core = "1.0.2"
tokio = { version = "1.25.0", features = ["macros", "rt"] }
